### ISSUE TITLE
Update `dwm` version

### ISSUE THREAD

**Issue by rawhuul** [load1n9/caviar#10]
Hey, currently `caviar` is using outdated version of `dwm` which throws error while running:

```js
import SCANCODE_WIN from "./scancode_win.json" assert { type: "json" };

  at https://deno.land/x/dwm@0.3.3/src/platform/glfw/window.ts:64:1
```

which is now fixed in recent update of `dwm`

**Comment by load1n9** [comment]
forgot to update this repo after update dwm, will get on this shortly

**Comment by rawhuul** [comment]
Cool, thanks

**Comment by load1n9** [comment]
published a new release, thank you for reminding me! props to you
