### ISSUE TITLE
Compiling shader

### ISSUE THREAD

**Issue by hoverek-yt** [load1n9/caviar#4]
![image](https://user-images.githubusercontent.com/89012686/174050716-df97152c-6c14-4faa-baae-98185d8e839c.png)
"An error occurred compiling the shaders: 0(2) : error C7573: OpenGL/ES requires precision specifier on this float type (there is no default precision)"

**Comment by load1n9** [comment]
been dealing with that aswell on some devices trying to find a solution at the moment

**Comment by load1n9** [comment]
should be fixed!
